service: bitcoin-service

plugins:
  - serverless-python-requirements
  - serverless-wsgi
custom:
  wsgi:
    app: src/bitcoin-service/app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.6
  lambdaHashingVersion: 20201221
  stage: dev
  profile: aws-reachgopi
  region: us-west-1

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

package:
  exclude:
    - node_modules/**
    - venv/**